done
SerhiiOnyshchenko/team-project-filmoteka pull request #14
Opened 2022-06-12 20:25 UTC by KizievDmitriy

2022-06-12 21:15 UTC, SerhiiOnyshchenko requested changes
Що за дивні назви? openn? hiddenn? backdropp?

2022-06-13 07:33 UTC, SerhiiOnyshchenko requested changes

2022-06-13 07:33 UTC, SerhiiOnyshchenko commented on src/js/footerModal.js
> +  return;
ретурн не потрібен

2022-06-13 07:33 UTC, SerhiiOnyshchenko commented on src/js/footerModal.js
> +  document.addEventListener('click', backdropp);
це не потріюне в тебе слухач на beckdrop

2022-06-13 07:33 UTC, SerhiiOnyshchenko commented on src/js/footerModal.js
> +  document.removeEventListener('click' , backdropp)
це не потрібне

2022-06-13 09:50 UTC, KizievDmitriy commented on src/js/footerModal.js
> +  return;
done

2022-06-13 09:50 UTC, KizievDmitriy commented on src/js/footerModal.js
> +  document.addEventListener('click', backdropp);
done

2022-06-13 09:50 UTC, KizievDmitriy commented on src/js/footerModal.js
> +  document.removeEventListener('click' , backdropp)
done

2022-06-13 10:04 UTC, SerhiiOnyshchenko commented
11 лінія не видалив
document.addEventListener('click', backdropp);

2022-06-13 10:05 UTC, SerhiiOnyshchenko commented
22 лінія потрібно було залишити

  document.removeEventListener('keydown', eventKeydown);

2022-06-13 10:06 UTC, SerhiiOnyshchenko requested changes

2022-06-13 10:06 UTC, SerhiiOnyshchenko commented on src/js/footerModal.js
> -  document.removeEventListener('keydown', eventKeydown);
document.removeEventListener('keydown', eventKeydown);

поверни

2022-06-13 11:54 UTC, KizievDmitriy commented on src/js/footerModal.js
> -  document.removeEventListener('keydown', eventKeydown);
done

2022-06-13 11:59 UTC, SerhiiOnyshchenko approved these changes

2022-06-13 11:59 UTC, merged