Feature ft 16
SerhiiOnyshchenko/team-project-filmoteka pull request #37
Opened 2022-06-16 18:54 UTC by NataliaMonasturska

2022-06-16 19:54 UTC, SerhiiOnyshchenko requested changes
фотки постера всі видали, залиш тільки Rectangle2.jpg

2022-06-16 19:54 UTC, SerhiiOnyshchenko commented on src/partials/modal.html
> +     </picture>
<picture>
         <source
             srcset="./images/modalFilm/Rectangle.jpg 1x,
             ./images/modalFilm/Rectangle2.jpg 2x"
             media="(min-width: 1024px)">
         <source
             srcset="./images/modalFilm/Rectangle-tab.jpg  1x, 
                     ./images/modalFilm/Rectangle-tab2.jpg  2x"
             media="(min-width: 768px)">
         <source
             srcset="./images/modalFilm/Rectangle-mob.jpg  1x, 
         ./images/modalFilm/Rectangle-mob2.jpg 2x"
             media="(min-width: 320px)">
         <img src="./images/modalFilm/Rectangle2.jpg" 
         alt="https://www.reelviews.net/resources/img/default_poster.jpg" />
     </picture>

це все зайве видали.
валиш тільки:
```
         <img src="./images/modalFilm/Rectangle2.jpg" 
         alt="https://www.reelviews.net/resources/img/default_poster.jpg" />
```
але значення альт зміни на "movie poster"

2022-06-16 19:54 UTC, SerhiiOnyshchenko commented on src/partials/modal.html
> +     <div class="btn-container">
кнопки потрібно прижати до низу.
бо коли буде мало тексту в about вони будуть підпригувати

2022-06-16 19:54 UTC, SerhiiOnyshchenko commented on src/sass/layouts/_modal.scss
> +margin: auto;
це зайве, видали.

2022-06-16 19:54 UTC, SerhiiOnyshchenko commented on src/sass/layouts/_modal.scss
> +.btn-close{
на кнопку добав якийсь ховер ефект

2022-06-16 19:54 UTC, SerhiiOnyshchenko commented on src/sass/layouts/_modal.scss
> +   height: 940px;
а тут 
flex-direction: row;

2022-06-16 19:54 UTC, SerhiiOnyshchenko commented on src/sass/layouts/_modal.scss
> +  .image-container {
вилали position: absolute;
і всі top і left

2022-06-16 19:54 UTC, SerhiiOnyshchenko commented on src/sass/layouts/_modal.scss
> +.container-context{
вилали position: absolute;
і всі top і left

для відсупів задавай подінги

2022-06-16 20:34 UTC, NataliaMonasturska commented on src/partials/modal.html
> +     </picture>
исправлено

2022-06-16 20:41 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +margin: auto;
ок.толькоэто не мой код)

2022-06-16 21:20 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +.btn-close{
есть

2022-06-16 21:29 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +font-style: normal;
есть

2022-06-16 21:30 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +font-style: normal;
+

2022-06-16 21:30 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +font-style: normal;
+

2022-06-16 21:30 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +font-style: normal;
+

2022-06-16 21:31 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +font-style: normal;
+

2022-06-16 21:32 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +font-style: normal;
есть

2022-06-16 21:32 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +font-style: normal;
есть

2022-06-16 21:33 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +font-style: normal;
есть

2022-06-16 21:33 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +font-style: normal;
есть

2022-06-16 21:34 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +margin: auto;
есть

2022-06-16 22:45 UTC, NataliaMonasturska commented on src/partials/modal.html
> +         <use xlink:href='./images/symbol-defs.svg#icon-close' width="125%" height="125%"></use>
есть

2022-06-16 22:46 UTC, NataliaMonasturska commented on src/partials/modal.html
> +     <div class="btn-container">
есть

2022-06-17 10:40 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +position: relative;
есть

2022-06-17 10:45 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +   height: 940px;
есть

2022-06-17 10:45 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +  .image-container {
есть

2022-06-17 10:47 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +.container-context{
есть

2022-06-17 10:54 UTC, NataliaMonasturska commented on src/sass/layouts/_modal.scss
> +}
есть

2022-06-17 14:12 UTC, SerhiiOnyshchenko approved these changes

2022-06-17 14:13 UTC, merged