FT-24: dark mode created
SerhiiOnyshchenko/team-project-filmoteka pull request #50
Opened 2022-06-18 20:08 UTC by LadyNenAdams

2022-06-18 21:17 UTC, SerhiiOnyshchenko requested changes

2022-06-18 21:17 UTC, SerhiiOnyshchenko commented on src/sass/layouts/_header.scss
> +	background-color: $primary-color;
як по мені то занадто чорне) 
спробуй ось такий колір `#000000af`

2022-06-18 21:17 UTC, SerhiiOnyshchenko commented on src/sass/layouts/_header.scss
> +	color: #fff;
ти тут двічі прописала більй колір

2022-06-18 21:17 UTC, SerhiiOnyshchenko commented on src/sass/layouts/_header.scss
> +	border: none;
background-color: transparent;
	border: none;
position: relative;
це повидаляй

2022-06-18 21:17 UTC, SerhiiOnyshchenko commented on src/sass/layouts/_header.scss
> +.mode {
цьому класу також додай 
@include displayFlex():

2022-06-18 21:17 UTC, SerhiiOnyshchenko commented on src/sass/layouts/_header.scss
> +	padding: 5px;
це видали 
	text-align: center;
	padding: 5px;
	і задай висоту 25px і ширину 35px
допиши
@include displayFlex():
це щоб відцентрувати і щоб не пригала кнопка при переключанні

2022-06-18 21:17 UTC, SerhiiOnyshchenko commented on src/sass/layouts/_header.scss
> +.change {
дадай ховер і фокус на кнопку

2022-06-19 13:46 UTC, LadyNenAdams commented on src/sass/layouts/_header.scss
> +.mode {
Если это сделать, то сильно летит всё внутри кнопки

2022-06-19 15:35 UTC, SerhiiOnyshchenko approved these changes

2022-06-19 15:35 UTC, merged